### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mukkumukesh** [facebookincubator/spectrum#169] opened 2019-05-09 05:54 UTC
Update my application from play store with the `app bundle`

Here is the exception we find from crashlytics details:

Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libspectrumpluginjpeg.so
com.facebook.soloader.SoLoader.doLoadLibraryBySoName

`com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:564)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:500)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
com.facebook.spectrum.plugins.SpectrumPluginJpeg.ensureLoadedAndInitialized (SpectrumPluginJpeg.java:31)
com.facebook.spectrum.plugins.SpectrumPluginJpeg.get (SpectrumPluginJpeg.java:48)
com.package.android.activities.application.onCreate (application.java:59)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1126)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:6097)
android.app.ActivityThread.-wrap1 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1791)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:7000)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:441)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
`

**Comment by mukkumukesh** [comment] 2019-05-09 05:54
Please help asap. I am stuck

**Comment by lambdapioneer** [comment] 2019-05-13 22:11
Closing as duplicate of https://github.com/facebookincubator/spectrum/issues/43 (replied there)

**Closed by lambdapioneer** 2019-05-13 22:11 UTC
