### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by jenishbhalala** [facebookincubator/spectrum#29] opened 2019-01-30 11:05 UTC
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: ../Library/Developer/CoreSimulator/Devices/5FDE9AE0-73B1-40C4-88A2-49135AA4A539/data/Containers/Bundle/Application/2F271AC6-0FD5-4B41-9217-ED87AA5D13CB/SpectrumKitSample-iOS.app/SpectrumKitSample-iOS
  Reason: image not found #24

**Comment by cuva** [comment] 2019-01-30 11:45
Hi @jenishbhalala - thanks for reporting the issue. Could you let me know which version of Xcode / iOS are you using so I can reproduce the issue? It seems to work fine with Xcode 10.1 and iOS 12 for both simulator and device.

Thanks!

**Comment by jenishbhalala** [comment] 2019-02-01 07:03
xcode 10.0, iPhone XS and  simulator 10.0

**Comment by cuva** [comment] 2019-02-04 14:08
Thanks for the answer @jenishbhalala. I am still not able to reproduce the issue. I've got a couple of things I'd love you to try to help be pinpoint the origin:

1) Try a full clean (`Opt+Shift+Cmd+K`) and re-run (`Cmd+R`). Check if it changes anything. Otherwise,
2) Navigate to SpectrumKitSample's target build settings and search for `LD_RUNPATH_SEARCH_PATHS` and tell me the value it has. It should be `@executable_path/Frameworks`. Otherwise,
3) Do a full build and navigate to the product (Right click on `Products/SpectrumKitSample-iOS.app` in the left navigator in Xcode, `Show In Finder`, Right click on the executable and `Show Package Contents` and navigate to the `Frameworks` folder. Ensure `libswiftAVFoundation.dylib` is present. Otherwise,
4) Add the following line in `SpectrumKit.podspec` line 23: `spec.frameworks = 'UIKit', 'CoreGraphics', 'AVFoundation'` Then head in `ios/SpectrumKitSample`, run `pod install` and re-try to launch the sample app. Does it change anything?

Thanks!

**Comment by cuva** [comment] 2021-05-07 07:59
Closing since no reply.

**Closed by cuva** 2021-05-07 07:59 UTC
Labels: needs-details
