### ISSUE TITLE
libpng linker command failure when running on iOS

### ISSUE THREAD

**Issue by marcusbuffett** [facebookincubator/spectrum#24] opened 2019-01-21 18:31 UTC
I tried to install SpectrumKit on iOS with the following in my Podfile:
```
    pod 'SpectrumKit'
```

The Podfile.lock shows these dependencies got installed:
``` - spectrum-folly (2018.11.12.00)
  - SpectrumCore/Base (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
  - SpectrumCore/Plugins/Jpeg (1.0.0):
    - mozjpeg
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Base (~> 1.0.0)
  - SpectrumCore/Plugins/Png (1.0.0):
    - libpng
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Base (~> 1.0.0)
  - SpectrumCore/Plugins/Webp (1.0.0):
    - libwebp
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Base (~> 1.0.0)
  - SpectrumKit (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumKit/Plugins/Default (= 1.0.0)
  - SpectrumKit/Base (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Base
  - SpectrumKit/Plugins/Default (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumKit/Plugins/Jpeg
    - SpectrumKit/Plugins/Png
    - SpectrumKit/Plugins/Webp
  - SpectrumKit/Plugins/Jpeg (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Plugins/Jpeg
    - SpectrumKit/Base (~> 1.0.0)
  - SpectrumKit/Plugins/Png (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Plugins/Png
    - SpectrumKit/Base (~> 1.0.0)
  - SpectrumKit/Plugins/Webp (1.0.0):
    - spectrum-folly (~> 2018.11.12.00)
    - SpectrumCore/Plugins/Webp
    - SpectrumKit/Base (~> 1.0.0)
```

When I try to run the project, I get the following linker error:
```
Ld /Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Products/Debug-iphoneos/libpng/libpng.framework/libpng normal arm64 (in target: libpng)
    cd /Users/marcusbuffett/Documents/projects/popcam-ios/AirCam/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Products/Debug-iphoneos/libpng -F/Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Products/Debug-iphoneos/libpng -filelist /Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/libpng.build/Objects-normal/arm64/libpng.LinkFileList -install_name @rpath/libpng.framework/libpng -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/libpng.build/Objects-normal/arm64/libpng_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -lz -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/libpng.build/Objects-normal/arm64/libpng_dependency_info.dat -o /Users/marcusbuffett/Library/Developer/Xcode/DerivedData/AirCam-gjsekqrwaodsivfvypxjgiqbllga/Build/Products/Debug-iphoneos/libpng/libpng.framework/libpng

Undefined symbols for architecture arm64:
  "_png_init_filter_functions_neon", referenced from:
      _png_init_filter_functions in pngrutil.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I haven't changed what architectures my project is building for, from the defaults of an iOS project.

**Comment by cuva** [comment] 2019-01-22 11:38
Thanks for raising this issue @marcusbuffett! There indeed seems to be an issue with the `libpng` dependency we depend on not including the definition of arm specific functions. I'll be looking into getting this fixed upstream - in the meantime here's what can be done to temporarily mitigate the issue:

Inject `PNG_ARM_NEON_OPT=0` to the Cflags of `libpng` which disables arm specific functions:

```
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    if target.name == "libpng"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)', '-DPNG_ARM_NEON_OPT=0']
      end
    end
  end
end
```

Or only depend on the `Jpeg` & `Webp` plugins until we get it sorted by only adding to your podfile:

```
pod 'SpectrumKit/Plugins/Jpeg'
pod 'SpectrumKit/Plugins/Webp'
```

I'm actively looking to get this fixed or depend on another `libpng` pod - we'll be pushing a release and updating this issue as soon as it's done. Thanks again!

**Comment by janniklind** [comment] 2019-02-02 11:56
I can confirm that it works. I had the same problem, so I used only pod 'SpectrumKit/Plugins/Jpeg', but now I have included pod 'SpectrumKit/Plugins/Png' as well and the problem with libpng no longer appears. Thanks! 👍

**Comment by cuva** [comment] 2019-02-04 11:11
Awesome - thanks for confirming @janniklind!

I'll close this for now - @marcusbuffett feel free to re-open if this isn't fixed for you.

**Closed by cuva** 2019-02-04 11:11 UTC
Labels: bug
